import type { NextPage } from "next";
import Head from "next/head";
import Header from "components/Header";
import LeftSide from "components/LeftSide";
import RightSide from "components/RightSide";
import Post from "components/Post";
import Announce from "components/Announce";
import Footer from "components/Footer";
import Pagination from "components/Pagination";
import CookieWindow from "components/CookieWindow";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center w-full max-w-[1300px] pt-[40px] px-[20px] relative">
        <Header />
        <div className="middle w-full mt-[52px] flex flex-row items-start">
          <LeftSide />
          <div className="content grow flex flex-col space-y-[24px]">
            <Post
              title={"Understanding the reasons behind a successful startup"}
              description={
                "Going over the reasons why most successful startups should understand the basics of business instead of just launching into the void without any market study."
              }
              author={"Jessica Davidson"}
              ago={"12 hours ago"}
              date={"23/11/2021"}
              imageSrc={"/post-image.png"}
            />
            <Announce />
            <Post
              title={"I quit my job last year to pursue freelancing full time."}
              description={
                "Quitting my full time job was not an easy decision to make, but it was one that has changed my life 180 degrees. Here’s my story from A to Z."
              }
              author={"Jessica Davidson"}
              ago={"12 hours ago"}
              date={"20/11/2021"}
              imageSrc={"/post-image-1.png"}
            />
            <Pagination />
          </div>
          <RightSide />
        </div>
      </main>

      <Footer />

      <CookieWindow />
    </div>
  );
};

export default Home;
